# Generated by Django 5.0.6 on 2024-07-02 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cert_number", models.CharField(max_length=20, unique=True)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("year", models.CharField(blank=True, max_length=4)),
                ("brand", models.CharField(blank=True, max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("card_number", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("variety", models.CharField(blank=True, max_length=100)),
                ("grade_description", models.CharField(blank=True, max_length=100)),
                ("card_grade", models.CharField(blank=True, max_length=20)),
                ("total_population", models.IntegerField(blank=True, null=True)),
                ("population_higher", models.IntegerField(blank=True, null=True)),
                ("front_image_url", models.URLField(blank=True)),
                ("back_image_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
